[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=0

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =

build_src_filter = +<*> -<.git/> -<.svn/> -<example/> -<examples/> -<test/> -<tests/>
