/*
 * Sprite Data Format and Compression Tools
 * 
 * This file defines the format for compressed sprite data and provides
 * utilities for creating sprite sheets for the eye display system.
 * 
 * MEMORY USAGE OPTIMIZATION:
 * - Uncompressed: 240x240x2 = 115,200 bytes per frame
 * - RLE Compressed: ~5,000-20,000 bytes per frame (5-20x compression)
 * - 4-bit Palette: 240x240/2 + 32 = 28,832 bytes per frame (4x compression)
 * - 8-bit Palette: 240x240 + 512 = 58,112 bytes per frame (2x compression)
 * 
 * RECOMMENDED WORKFLOW:
 * 1. Create eye images at 240x240 pixels
 * 2. Use provided Python script to convert to compressed format
 * 3. Include generated .h file with sprite data
 * 4. Load sprites using load_sprite_data() function
 */

#pragma once
#include <Arduino.h>

// Example compressed sprite data (placeholder)
// In real usage, this would be generated by conversion tools

// Example RLE-compressed idle eye frame
const uint8_t PROGMEM sprite_idle_rle[] = {
    // Format: [count][color_low][color_high], repeat...
    // This is just example data - real data would be much larger
    50, 0x00, 0x00,   // 50 pixels of black
    30, 0xDE, 0xF7,   // 30 pixels of sclera color
    10, 0x45, 0x29,   // 10 pixels of iris
    5,  0x00, 0x00,   // 5 pixels of pupil
    // ... continue for full frame
};

// Example 4-bit palette for realistic eyes
const uint16_t PROGMEM realistic_eye_palette[] = {
    0x0000, // 0: Black (pupil/outline)
    0x1082, // 1: Dark brown (iris outer)
    0x2945, // 2: Medium brown (iris)
    0x4A49, // 3: Light brown (iris inner)
    0xF7DE, // 4: Sclera white
    0xFFFF, // 5: Highlight white
    0x8C71, // 6: Eyelid pink
    0x6B4D, // 7: Skin tone
    0x39C7, // 8: Shadow gray
    0xC618, // 9: Vessel red (subtle)
    0xE73C, // 10: Bright red (irritated)
    0x07E0, // 11: Green (alien/fantasy)
    0x001F, // 12: Blue (fantasy)
    0xF81F, // 13: Magenta (fantasy)
    0xFFE0, // 14: Yellow (fantasy)
    0x7BEF  // 15: Light gray
};

// Example sprite frame definitions
struct ExampleSpriteData {
    // Idle eye frame
    static const uint8_t idle_frame_rle[];
    static const uint16_t idle_frame_size;
    
    // Blink sequence frames
    static const uint8_t blink_frame1_rle[];
    static const uint8_t blink_frame2_rle[];
    static const uint8_t blink_frame3_rle[];
    
    // Look direction frames
    static const uint8_t look_left_rle[];
    static const uint8_t look_right_rle[];
    static const uint8_t look_up_rle[];
    static const uint8_t look_down_rle[];
};

/*
 * PYTHON CONVERSION SCRIPT EXAMPLE:
 * 
 * Save this as convert_to_sprites.py:
 * 
 * ```python
 * from PIL import Image
 * import os
 * 
 * def rgb565_convert(r, g, b):
 *     """Convert RGB888 to RGB565"""
 *     return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
 * 
 * def rle_compress(pixels):
 *     """Simple RLE compression"""
 *     compressed = []
 *     if not pixels:
 *         return compressed
 *     
 *     current_color = pixels[0]
 *     count = 1
 *     
 *     for pixel in pixels[1:]:
 *         if pixel == current_color and count < 255:
 *             count += 1
 *         else:
 *             compressed.extend([count, current_color & 0xFF, (current_color >> 8) & 0xFF])
 *             current_color = pixel
 *             count = 1
 *     
 *     compressed.extend([count, current_color & 0xFF, (current_color >> 8) & 0xFF])
 *     return compressed
 * 
 * def convert_image_to_sprite(image_path, output_name):
 *     """Convert PNG/JPG to compressed sprite data"""
 *     img = Image.open(image_path).convert('RGB')
 *     img = img.resize((240, 240), Image.LANCZOS)
 *     
 *     pixels = []
 *     for y in range(240):
 *         for x in range(240):
 *             r, g, b = img.getpixel((x, y))
 *             pixels.append(rgb565_convert(r, g, b))
 *     
 *     compressed = rle_compress(pixels)
 *     
 *     # Generate C array
 *     with open(f"{output_name}.h", "w") as f:
 *         f.write(f"const uint8_t PROGMEM {output_name}_rle[] = {{\n")
 *         for i in range(0, len(compressed), 12):
 *             line = "    " + ", ".join(f"0x{b:02X}" for b in compressed[i:i+12]) + ",\n"
 *             f.write(line)
 *         f.write("};\n")
 *         f.write(f"const uint16_t {output_name}_size = {len(compressed)};\n")
 *     
 *     print(f"Converted {image_path} -> {output_name}.h ({len(compressed)} bytes)")
 * 
 * # Usage example:
 * # convert_image_to_sprite("eye_idle.png", "sprite_idle")
 * # convert_image_to_sprite("eye_blink1.png", "sprite_blink1")
 * ```
 * 
 * USAGE INSTRUCTIONS:
 * 1. Create your eye images (240x240 PNG format)
 * 2. Run: python convert_to_sprites.py
 * 3. Include the generated .h files
 * 4. Update load_sprite_data() to reference your actual sprite arrays
 * 
 * MEMORY BUDGET PLANNING:
 * - Target: ~3MB flash available for sprites
 * - Each RLE frame: ~10KB average
 * - Capacity: ~300 frames of high-quality realistic eyes
 * - Recommended: 20-50 frames for diverse eye animations
 */

// Example function to calculate memory usage
inline uint32_t calculate_sprite_memory_usage(uint8_t frame_count, uint16_t avg_compressed_size) {
    uint32_t total = frame_count * (sizeof(SpriteFrame) + avg_compressed_size);
    return total;
}

// Example animation sequences you could implement:
// - Idle: 1-3 frames with slight variations
// - Blink: 5-7 frames (open -> squint -> closed -> squint -> open)
// - Look directions: 3-5 frames each direction
// - Emotions: Happy, angry, confused, sleepy (3-5 frames each)
// - Special effects: Matrix digital rain, fire, ice, etc.